apiVersion: v1
kind: Secret
metadata:
  name: noc-agent-be-secret
  namespace: gruve-noc
type: Opaque
stringData:
  MERAKI_API_KEY: "86d9dbe8fb3c0adf0399fb1a697a6baa6ff21da8"
  MERAKI_ORG_ID: "1655564"
  MERAKI_NETWORK_ID: ""
  LLM_API_KEY: "unused"
  MONGO_URI: "mongodb://gruve_user:Gruve@NOC2026!@mongodb.gruve-noc.svc.cluster.local:27017/gruve_noc?authSource=admin"
  QDRANT_API_KEY: "7e8803b91f4d1f2b46504aa7bb6a4496d49e105fa1239dd766350576a8ff72dcc929f9f43d49f5c8fd84efe3eb72eea038d740633116615cf9a0efdafb2e4987"
  SNOW_USERNAME: "admin"
  SNOW_PASSWORD: "c%%tv4yUII5P"
  AAP_TOKEN: ""
