apiVersion: v1
kind: Secret
metadata:
  name: noc-agent-be-secret
  namespace: gruve-noc
type: Opaque
stringData:
  MERAKI_API_KEY: "86d9dbe8fb3c0adf0399fb1a697a6baa6ff21da8"
  MERAKI_ORG_ID: "1655564"
  MERAKI_NETWORK_ID: ""
  LLM_API_KEY: "unused"
  MONGO_URI: "mongodb://gruve_user:Gruve2026@mongodb.gruve-noc.svc.cluster.local:27017/gruve_noc?authSource=admin"
  QDRANT_API_KEY: "7e8803b91f4d1f2b46504aa7bb6a4496d49e105fa1239dd766350576a8ff72dcc929f9f43d49f5c8fd84efe3eb72eea038d740633116615cf9a0efdafb2e4987"
  SNOW_USERNAME: "admin"
  SNOW_PASSWORD: "K/-nhCT98gG"
  AAP_TOKEN: "esBXwLQlbRM7QgLguqeqWl231utzVX"
  GEMINI_API_KEY: "AIzaSyA8RPIXv5F8AuelMr78g2ENv4ohO8Ixq7s"
  GEMINI_MODEL: "gemini-2.5-flash"
  LLM_PROVIDER: "gemini"
  PROMETHEUS_URL: "https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
  PROMETHEUS_TOKEN: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkptWlJ1a0JIVTBaQ3NsbFB3NThnUWR1b1JySXk3VUFTai13RDdvSGFNeTAifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MjA5Mzc2MDI1NywiaWF0IjoxNzc4NDAwMjU3LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiIxMzMwYTg1OS03OGQ0LTRhZTAtYWFlOS01MjIyMTE2OGZhMGQiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImdydXZlLW5vYyIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJwcm9tZXRoZXVzLXJlYWRlciIsInVpZCI6IjE0NWM5YjUyLTY4MGEtNGJlNy1hMjE4LWIyNzEzYWU4MmE2OSJ9fSwibmJmIjoxNzc4NDAwMjU3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Z3J1dmUtbm9jOnByb21ldGhldXMtcmVhZGVyIn0.Fz1X4mAUm7ZknnH2H0pvBbscR3jmJtziEQRITlASSINV-cdFhrIoUShNZze2fVQsFG_D3OPDYa1cHn9DxEXisDvfv4BUDeCBb_ZN1Pvj2D6SjcWt8xwKcR48_aO2hLrrJ2G_LEeoG434QxooI91zdMOEye-D7Zs79i5gN4qCpK-NRzgWigll6za5UMuu08UTyEvGAOIxfyfM1HetQWj4yxUrUFmVYHfcEXwaXOJ0PLrGdpBN0oOobxYEGx9btoMXIJWIkgWfrl5coEFJb3POoxDEZgzIiXEMyjep4rctLuhWJkC3n44CWcEezHuY71JyFNr34BckR92wjUa38xtFSwz-ryh9ubKWgqDAXOXkOUs3BTonUzYxS5gJch3corxhOLnCC4StKt7BMI0fd6S0TBgS8Q-9jE9qzo7zrII9fNncsKKdeyJFujkFB74GgcwdhT5rOYdLhv3DduJZKEPfr9OBGbbj4qxzTjV4QNiHb1q6SrGD_1k6tXb9mhAorIiYdG9yTCm2NGxfIc3lz1bQ0035B4Jq99GSAJFMk9830GbPL8SBolMT1MfQO7halfJAIy7vbeODN-F4kaq2BvqJVlSoS4DubU6yxr_H4kNXVVg4jSoOUDZcvgn7b4mhB_Zaeq9ZOeXT7veB4ljyhv_uWV4eZbi87a_J-E85P31L6nU"
