apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: openshift-monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: gruve-noc-vms
      static_configs:
        - targets:
          - 10.7.51.135:9100
          - 10.7.51.136:9100
          - 10.7.51.137:9100
          - 10.7.51.32:9100
          labels:
            job: gruve-noc-vms
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
        - source_labels: [__address__]
          regex: '([^:]+):.*'
          target_label: node_ip
          replacement: '$1'
